name: paper2code

services:

  db:
    image: postgres:17
    container_name: paper2code_db
    env_file:
      - apps/server/.env
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - paper2code_network

  web:
    container_name: paper2code_web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - apps/web/.env
    depends_on:
      - server
    networks:
      - paper2code_network

  server:
    container_name: paper2code_server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3000:3000"
      - "4983:4983"
    env_file:
      - apps/server/.env
    volumes:
      - ./apps/server/.env:/app/apps/server/.env
      - ./credentials:/app/credentials
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - cpp_runner
      - java_runner
      - python_runner
    networks:
      - paper2code_network

  cpp_runner:
    container_name: cpp_script_runner
    build:
      context: apps/server
      dockerfile: Dockerfile.cpp
    init: true
    restart: unless-stopped
    networks:
      - paper2code_network

  java_runner:
    container_name: java_script_runner
    build:
      context: apps/server
      dockerfile: Dockerfile.java
    init: true
    restart: unless-stopped
    networks:
      - paper2code_network

  python_runner:

    build:
      context: apps/server
      dockerfile: Dockerfile.python
    init: true
    restart: unless-stopped
    networks:
      - paper2code_network

volumes:
  postgres_data:
    name: paper2code_postgres_data

networks:
  paper2code_network:
    name: paper2code_network
