name: paper2code
services:
  cpp_runner:
    build:
      context: .
      dockerfile: Dockerfile.cpp
    # command: tail -f /dev/null
    container_name: cpp_script_runner
    init: true
    restart: unless-stopped

  java_runner:
    build:
      context: .
      dockerfile: Dockerfile.java
    container_name: java_script_runner
    init: true
    restart: unless-stopped

  python_runner:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python_script_runner
    init: true
    restart: unless-stopped
